### ISSUE TITLE
NodeSearch Bugs

### ISSUE THREAD

**Issue by willzeng** [willzeng/WikiNets#18]
- When you add a node with the NodeSearch celestrium plugin it does not assign the correct ID to the node (it just defaults to -1 at present)
- Make sure that when you add a node this way it automatically adds the links
- Use VisualSearch.js

**Comment by backens** [comment]
implemented in e218b8321072691414193241d1a3ec5d49172a24 though there are still some small changes to be made (e.g. dynamically update facets and values)

**Comment by backens** [comment]
Adding nodes via NodeSearch currently fails when there are multiple keys that differ only in capitalization (e.g. "title" and "Title")

**Comment by willzeng** [comment]
Maybe it would make sense to solve this by making keys case-insensitive. This could be done by converting them to lowercase with the first character capitalized in Neo4jDataController before putting them in the database.  

What do you think?

**Comment by backens** [comment]
The problem comes from VisualSearch internally converting keys to lower 
case and me using some of the internal functions because it seemed the 
easiest way to parse the search input. I might be able to figure out a 
different way of parsing it that won't have that problem.

I'd rather not convert all keys to lower case because people might want 
to use camel case to get around the issue of not being allowed spaces in 
property names.

**Comment by backens** [comment]
fixed in b40031fa20387f37b6e2e0feace5c4651b349492
