### ISSUE TITLE
Make sure all information is displayed after editing a node

### ISSUE THREAD

**Issue by backens** [willzeng/WikiNets#87]
Currently if Last_Edit_Date and color are added to a node for the first time, they don't immediately show up in the information view. They do show up after clicking "Edit Node" again, and then "Cancel".

**Comment by CalvinFong** [comment]
Currently, the colors work using hexadecimal values so i hid the values. Likewise, I hid Last_Edit_Date because the format was really long and look pretty messy in the edit box.
It is possible for me to display the names of the colors and a shortened version of Last_Edit_Date in the information view if you would like.

I think the reason they display after clicking edit and then cancelling is because I forgot to use blacklist. I've changed that (as well as changing the variable names to "_Last_Edit_Date" etc.) but haven't committed the changes yet.

**Comment by CalvinFong** [comment]
That was meant to be "_Last_Edit_Date"

**Comment by backens** [comment]
@CalvinFong Can we consider this issue closed as of 0c49d29cbb183cc209ad754358977f2494b4fa5c ?

**Comment by backens** [comment]
Currently we're not displaying the colour property at all outside editing, but then that may very well not be necessary. Thoughts?

**Comment by CalvinFong** [comment]
I forgot to change displays for ListView so I'll close it with the next commit. I'll display the colour property as well

**Comment by willzeng** [comment]
I think it probably isn't necessary to include it as a text field as we are
showing it graphical on the GraphView itself and in the color picker plugin
in Node Edit.

**Comment by CalvinFong** [comment]
ce5b67f8a14c15926792a91d0d0444137aa63f5e
